//Source file: X:/SMC/source/AOD/AOD_Frame/iAOD_Interface.idl

#ifndef __IAOD_INTERFACE_DEFINED
#define __IAOD_INTERFACE_DEFINED

/* CmIdentification
  %X% %Q% %Z% %W% */

#include "SMC_Frame\iSMC_DataProvider.idl"

	
interface iCORBA_Interfaces : iSMC_DataProvider {
};

#endif
