#ifndef _cCBS_StdEventLogFrame_DestCodes_h_
#define _cCBS_StdEventLogFrame_DestCodes_h_
class cCBS_StdEventLogFrame_DestCodes
{
public:
static const long long AODBotLine;
static const long long AOD_1BotLine;
static const long long AOD_2BotLine;
static const long long AOD_3BotLine;
static const long long AOD_4BotLine;
static const long long AOD_5BotLine;
static const long long BOFBotLine;
static const long long BOF_1BotLine;
static const long long BOF_2BotLine;
static const long long BOF_3BotLine;
static const long long BOF_4BotLine;
static const long long BOF_5BotLine;
static const long long ConArcBotLine;
static const long long ConArc_1BotLine;
static const long long ConArc_2BotLine;
static const long long ConArc_3BotLine;
static const long long ConArc_4BotLine;
static const long long ConArc_5BotLine;
static const long long EAFBotLine;
static const long long EAF_1BotLine;
static const long long EAF_2BotLine;
static const long long EAF_3BotLine;
static const long long EAF_4BotLine;
static const long long EAF_5BotLine;
static const long long LFBotLine;
static const long long LF_1BotLine;
static const long long LF_2BotLine;
static const long long LF_3BotLine;
static const long long LF_4BotLine;
static const long long LF_5BotLine;
static const long long RHBotLine;
static const long long RH_1BotLine;
static const long long RH_2BotLine;
static const long long VDBotLine;
static const long long VD_1BotLine;
static const long long VD_2BotLine;
static const long long HMDBotLine;
static const long long HMD_1BotLine;
static const long long HMD_2BotLine;
static const long long HMD_3BotLine;
static const long long HMD_4BotLine;
static const long long HMD_5BotLine;
static const long long LTSBotLine;
static const long long LTS_1BotLine;
static const long long LTS_2BotLine;
static const long long LTS_3BotLine;
static const long long LTS_4BotLine;
static const long long LTS_5BotLine;
static const long long CCSBotLine;
static const long long CCS_1BotLine;
static const long long CCS_2BotLine;
static const long long CCS_3BotLine;
static const long long CCS_4BotLine;
static const long long CCS_5BotLine;
static const long long CASBotLine;
static const long long CAS_1BotLine;
static const long long CAS_2BotLine;
static const long long SAFBotLine;
static const long long SAF_1BotLine;
static const long long SAF_2BotLine;
static const long long SAF_3BotLine;
static const long long SAF_4BotLine;
static const long long SAF_5BotLine;
static const long long AllBotLines;
static const long long ComputerRoom;
static const long long ALL;
};
#endif
