//## Copyright (C) 2009 SMS Siemag AG, Germany 
//## Version generated by DBClassCodeUtility BETA 0.6.3 
//## ALL METHODS MARKED AS - //##DBClassCodeUtility - WILL BE OVERWRITTEN, IF DB CLASS RE-GENERATED 
//## MANUALLY IMPLEMENTED METHODS MUST BE LOCATED BELOW THE MARK - "YOUR-CODE" - 


#include "CGC_PARAM_TYPE.h"


//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGC_PARAM_TYPE::TYPE("TYPE");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGC_PARAM_TYPE::TYPENAME("TYPENAME");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGC_PARAM_TYPE::PARAMTYPEDESCR("PARAMTYPEDESCR");

//##DBClassCodeUtility ! DO NOT EDIT !
CGC_PARAM_TYPE::CGC_PARAM_TYPE(cCBS_StdConnection* Connection)
:CSMC_DBData("GC_PARAM_TYPE",Connection)
{
  //please implement virtual method, to initialize your members  
  doOnConstruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
CGC_PARAM_TYPE::CGC_PARAM_TYPE(cCBS_Connection* Connection)
:CSMC_DBData("GC_PARAM_TYPE",Connection)
{
  //please implement virtual method, to initialize your members  
  doOnConstruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
CGC_PARAM_TYPE::CGC_PARAM_TYPE()
:CSMC_DBData("GC_PARAM_TYPE")
{
  //please implement virtual method, to initialize your members  
  doOnConstruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
CGC_PARAM_TYPE::~CGC_PARAM_TYPE()
{
  //please implement virtual method, to destruct your members
  doOnDestruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
//##Parameter Type
long CGC_PARAM_TYPE::getTYPE(long Row)
{
  return getLong(CGC_PARAM_TYPE::TYPE, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGC_PARAM_TYPE::setTYPE(long value)
{
  setLong(CGC_PARAM_TYPE::TYPE, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
//##Name as defined in eParamTypes.h in SMM
std::string CGC_PARAM_TYPE::getTYPENAME(long Row)
{
  return getString(CGC_PARAM_TYPE::TYPENAME, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGC_PARAM_TYPE::setTYPENAME(const std::string& value)
{
  setString(CGC_PARAM_TYPE::TYPENAME, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
std::string CGC_PARAM_TYPE::getPARAMTYPEDESCR(long Row)
{
  return getString(CGC_PARAM_TYPE::PARAMTYPEDESCR, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGC_PARAM_TYPE::setPARAMTYPEDESCR(const std::string& value)
{
  setString(CGC_PARAM_TYPE::PARAMTYPEDESCR, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
bool CGC_PARAM_TYPE::select(long TYPE)
{
  cleanWhereStatement();

  m_Statement = "Select * from " + m_TableName;

  addWhereClause(CGC_PARAM_TYPE::TYPE,TYPE);
  m_Statement += getWhereStatement() + ";";

  return CSMC_DBData::select();
}

//## ------------------------------------END-GENERATED-CODE---------------------- 

//## ------------------------------------YOUR-CODE------------------------------- 


