//## Copyright (C) 2009 SMS Siemag AG, Germany 
//## Version generated by DBClassCodeUtility BETA 0.6.3 
//## ALL METHODS MARKED AS - //##DBClassCodeUtility - WILL BE OVERWRITTEN, IF DB CLASS RE-GENERATED 
//## MANUALLY IMPLEMENTED METHODS MUST BE LOCATED BELOW THE MARK - "YOUR-CODE" - 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CGC_REBLOWCOOL_REASON_INCLUDED
#define _INC_CGC_REBLOWCOOL_REASON_INCLUDED

#include "CSMC_DBData.h"

class CGC_REBLOWCOOL_REASON
: public CSMC_DBData
{

public:
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string REASON;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string REBLOW_COOLING;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string REASON_BLOCON;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string DESCRIPTION;

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGC_REBLOWCOOL_REASON(cCBS_StdConnection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGC_REBLOWCOOL_REASON(cCBS_Connection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGC_REBLOWCOOL_REASON();

  //##DBClassCodeUtility ! DO NOT EDIT !
  ~CGC_REBLOWCOOL_REASON();

  //##DBClassCodeUtility ! DO NOT EDIT !
  std::string getREASON(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setREASON(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  long getREBLOW_COOLING(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setREBLOW_COOLING(long value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  long getREASON_BLOCON(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setREASON_BLOCON(long value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  std::string getDESCRIPTION(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setDESCRIPTION(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  bool select(const std::string& REASON);

  //## ----------------------------------END-GENERATED-CODE--------------------- 

  //## ----------------------------------YOUR-CODE------------------------------ 

};

#endif /* _INC_CGC_REBLOWCOOL_REASON_INCLUDED */
