//## Copyright (C) 2013 SMS Siemag AG, Germany 
//## Version generated by DBClassCodeUtility BETA 0.6.3 
//## ALL METHODS MARKED AS - //##DBClassCodeUtility - WILL BE OVERWRITTEN, IF DB CLASS RE-GENERATED 
//## MANUALLY IMPLEMENTED METHODS MUST BE LOCATED BELOW THE MARK - "YOUR-CODE" - 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CGCH_TREAT_TYPE_INCLUDED
#define _INC_CGCH_TREAT_TYPE_INCLUDED

#include "CSMC_DBData.h"

class CGCH_TREAT_TYPE
: public CSMC_DBData

{

public:
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string TREAT_TYPE;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string TREAT_TYPE_DESC;

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGCH_TREAT_TYPE(cCBS_StdConnection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGCH_TREAT_TYPE(cCBS_Connection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGCH_TREAT_TYPE();

  //##DBClassCodeUtility ! DO NOT EDIT !
  ~CGCH_TREAT_TYPE();

  //##DBClassCodeUtility ! DO NOT EDIT !
  long getTREAT_TYPE(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setTREAT_TYPE(long value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  std::string getTREAT_TYPE_DESC(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setTREAT_TYPE_DESC(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  bool select(long TREAT_TYPE);

  //## ----------------------------------END-GENERATED-CODE--------------------- 

  //## ----------------------------------YOUR-CODE------------------------------ 

};

#endif /* _INC_CGCH_TREAT_TYPE_INCLUDED */
