//## Copyright (C) 2009 SMS Siemag AG, Germany 
//## Version generated by DBClassCodeUtility BETA 0.6.3 
//## ALL METHODS MARKED AS - //##DBClassCodeUtility - WILL BE OVERWRITTEN, IF DB CLASS RE-GENERATED 
//## MANUALLY IMPLEMENTED METHODS MUST BE LOCATED BELOW THE MARK - "YOUR-CODE" - 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CGCL_STIRR_PHASE_INCLUDED
#define _INC_CGCL_STIRR_PHASE_INCLUDED

#include "CSMC_DBData.h"

class CGCL_STIRR_PHASE
: public CSMC_DBData
{

public:
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string PRACPHASE;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string FLAGDUR;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string PRACPHASEORDERNO;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string PRACPHASEDESCR;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string PRACPHASEMODEL;

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGCL_STIRR_PHASE(cCBS_StdConnection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGCL_STIRR_PHASE(cCBS_Connection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGCL_STIRR_PHASE();

  //##DBClassCodeUtility ! DO NOT EDIT !
  ~CGCL_STIRR_PHASE();

  //##DBClassCodeUtility ! DO NOT EDIT !
  std::string getPRACPHASE(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setPRACPHASE(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  long getFLAGDUR(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setFLAGDUR(long value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  long getPRACPHASEORDERNO(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setPRACPHASEORDERNO(long value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  std::string getPRACPHASEDESCR(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setPRACPHASEDESCR(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  std::string getPRACPHASEMODEL(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setPRACPHASEMODEL(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  bool select(const std::string& PRACPHASE);

  //## ----------------------------------END-GENERATED-CODE--------------------- 

  //## ----------------------------------YOUR-CODE------------------------------ 

  bool selectAllOrdered(std::string& ORDERBY);

  bool selectByPracPhaseModel(const std::string& PRACPHASEMODEL);

};

#endif /* _INC_CGCL_STIRR_PHASE_INCLUDED */
