//## Copyright (C) 2009 SMS Siemag AG, Germany 
//## Version generated by DBClassCodeUtility BETA 0.6.3 
//## ALL METHODS MARKED AS - //##DBClassCodeUtility - WILL BE OVERWRITTEN, IF DB CLASS RE-GENERATED 
//## MANUALLY IMPLEMENTED METHODS MUST BE LOCATED BELOW THE MARK - "YOUR-CODE" - 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CGT_GRADE_ANL_INCLUDED
#define _INC_CGT_GRADE_ANL_INCLUDED

#include "CSMC_DBData.h"

class CGT_GRADE_ANL
: public CSMC_DBData
{

public:
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string PLANT;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string STEELGRADECODE;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string AIMTYPE;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string ENAME;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string ANL;

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGT_GRADE_ANL(cCBS_StdConnection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGT_GRADE_ANL(cCBS_Connection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGT_GRADE_ANL();

  //##DBClassCodeUtility ! DO NOT EDIT !
  ~CGT_GRADE_ANL();

  //##DBClassCodeUtility ! DO NOT EDIT !
  //##Plant identifier
  std::string getPLANT(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setPLANT(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  //##Steel grade code
  std::string getSTEELGRADECODE(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setSTEELGRADECODE(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  //##Min, Max, Aim
  std::string getAIMTYPE(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setAIMTYPE(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  //##Element or slag compound name
  std::string getENAME(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setENAME(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  //##Analysis value
  double getANL(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setANL(double value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  bool select(const std::string& PLANT, const std::string& STEELGRADECODE, const std::string& AIMTYPE, const std::string& ENAME);

  //## ----------------------------------END-GENERATED-CODE--------------------- 

  //## ----------------------------------YOUR-CODE------------------------------ 

  bool deleteGrade(const std::string& STEELGRADECODE );

  bool writeAnalysis(const std::string& PLANT, const std::string& STEELGRADECODE, const std::string& AIMTYPE, seqAnalysis SeqAnalysis, bool Commit);

};

#endif /* _INC_CGT_GRADE_ANL_INCLUDED */
