//## Copyright (C) 2009 SMS Siemag AG, Germany 
//## Version generated by DBClassCodeUtility BETA 0.6.3 
//## ALL METHODS MARKED AS - //##DBClassCodeUtility - WILL BE OVERWRITTEN, IF DB CLASS RE-GENERATED 
//## MANUALLY IMPLEMENTED METHODS MUST BE LOCATED BELOW THE MARK - "YOUR-CODE" - 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CGT_ENG_UNIT_INCLUDED
#define _INC_CGT_ENG_UNIT_INCLUDED

#include "CSMC_DBData.h"

class CGT_ENG_UNIT
: public CSMC_DBData
{

public:
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string UNIT;

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGT_ENG_UNIT(cCBS_StdConnection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGT_ENG_UNIT(cCBS_Connection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CGT_ENG_UNIT();

  //##DBClassCodeUtility ! DO NOT EDIT !
  ~CGT_ENG_UNIT();

  //##DBClassCodeUtility ! DO NOT EDIT !
  //##Engineering unit
  std::string getUNIT(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setUNIT(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  bool select(const std::string& UNIT);

  //## ----------------------------------END-GENERATED-CODE--------------------- 

  //## ----------------------------------YOUR-CODE------------------------------ 

};

#endif /* _INC_CGT_ENG_UNIT_INCLUDED */
