//## Copyright (C) 2009 SMS Siemag AG, Germany 
//## Version generated by DBClassCodeUtility BETA 0.6.3 
//## ALL METHODS MARKED AS - //##DBClassCodeUtility - WILL BE OVERWRITTEN, IF DB CLASS RE-GENERATED 
//## MANUALLY IMPLEMENTED METHODS MUST BE LOCATED BELOW THE MARK - "YOUR-CODE" - 


#include "CGTE_PP_STIRR_SPEC.h"


//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::PLANT("PLANT");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::PLANTNO("PLANTNO");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::PRACNO("PRACNO");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::TREATMODENO("TREATMODENO");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::LIQ_ADD_AMOUNT("LIQ_ADD_AMOUNT");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::PRACPHASE("PRACPHASE");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::STEPNO("STEPNO");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::SPECEGY("SPECEGY");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::ELEC_ENERGY("ELEC_ENERGY");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::STIRRFLOW("STIRRFLOW");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::STIRRGASTYPE("STIRRGASTYPE");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_STIRR_SPEC::DISPLAY_ORDER("DISPLAY_ORDER");

//##DBClassCodeUtility ! DO NOT EDIT !
CGTE_PP_STIRR_SPEC::CGTE_PP_STIRR_SPEC(cCBS_StdConnection* Connection)
:CSMC_DBData("GTE_PP_STIRR_SPEC",Connection)
{
  //please implement virtual method, to initialize your members  
  doOnConstruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
CGTE_PP_STIRR_SPEC::CGTE_PP_STIRR_SPEC(cCBS_Connection* Connection)
:CSMC_DBData("GTE_PP_STIRR_SPEC",Connection)
{
  //please implement virtual method, to initialize your members  
  doOnConstruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
CGTE_PP_STIRR_SPEC::CGTE_PP_STIRR_SPEC()
:CSMC_DBData("GTE_PP_STIRR_SPEC")
{
  //please implement virtual method, to initialize your members  
  doOnConstruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
CGTE_PP_STIRR_SPEC::~CGTE_PP_STIRR_SPEC()
{
  //please implement virtual method, to destruct your members
  doOnDestruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
std::string CGTE_PP_STIRR_SPEC::getPLANT(long Row)
{
  return getString(CGTE_PP_STIRR_SPEC::PLANT, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setPLANT(const std::string& value)
{
  setString(CGTE_PP_STIRR_SPEC::PLANT, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_STIRR_SPEC::getPLANTNO(long Row)
{
  return getLong(CGTE_PP_STIRR_SPEC::PLANTNO, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setPLANTNO(long value)
{
  setLong(CGTE_PP_STIRR_SPEC::PLANTNO, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_STIRR_SPEC::getPRACNO(long Row)
{
  return getLong(CGTE_PP_STIRR_SPEC::PRACNO, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setPRACNO(long value)
{
  setLong(CGTE_PP_STIRR_SPEC::PRACNO, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_STIRR_SPEC::getTREATMODENO(long Row)
{
  return getLong(CGTE_PP_STIRR_SPEC::TREATMODENO, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setTREATMODENO(long value)
{
  setLong(CGTE_PP_STIRR_SPEC::TREATMODENO, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_STIRR_SPEC::getLIQ_ADD_AMOUNT(long Row)
{
  return getLong(CGTE_PP_STIRR_SPEC::LIQ_ADD_AMOUNT, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setLIQ_ADD_AMOUNT(long value)
{
  setLong(CGTE_PP_STIRR_SPEC::LIQ_ADD_AMOUNT, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
std::string CGTE_PP_STIRR_SPEC::getPRACPHASE(long Row)
{
  return getString(CGTE_PP_STIRR_SPEC::PRACPHASE, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setPRACPHASE(const std::string& value)
{
  setString(CGTE_PP_STIRR_SPEC::PRACPHASE, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_STIRR_SPEC::getSTEPNO(long Row)
{
  return getLong(CGTE_PP_STIRR_SPEC::STEPNO, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setSTEPNO(long value)
{
  setLong(CGTE_PP_STIRR_SPEC::STEPNO, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
double CGTE_PP_STIRR_SPEC::getSPECEGY(long Row)
{
  return getDouble(CGTE_PP_STIRR_SPEC::SPECEGY, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setSPECEGY(double value)
{
  setDouble(CGTE_PP_STIRR_SPEC::SPECEGY, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_STIRR_SPEC::getELEC_ENERGY(long Row)
{
  return getLong(CGTE_PP_STIRR_SPEC::ELEC_ENERGY, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setELEC_ENERGY(long value)
{
  setLong(CGTE_PP_STIRR_SPEC::ELEC_ENERGY, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
double CGTE_PP_STIRR_SPEC::getSTIRRFLOW(long Row)
{
  return getDouble(CGTE_PP_STIRR_SPEC::STIRRFLOW, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setSTIRRFLOW(double value)
{
  setDouble(CGTE_PP_STIRR_SPEC::STIRRFLOW, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
std::string CGTE_PP_STIRR_SPEC::getSTIRRGASTYPE(long Row)
{
  return getString(CGTE_PP_STIRR_SPEC::STIRRGASTYPE, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setSTIRRGASTYPE(const std::string& value)
{
  setString(CGTE_PP_STIRR_SPEC::STIRRGASTYPE, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_STIRR_SPEC::getDISPLAY_ORDER(long Row)
{
  return getLong(CGTE_PP_STIRR_SPEC::DISPLAY_ORDER, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_STIRR_SPEC::setDISPLAY_ORDER(long value)
{
  setLong(CGTE_PP_STIRR_SPEC::DISPLAY_ORDER, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
bool CGTE_PP_STIRR_SPEC::select(const std::string& PLANT, long PLANTNO, long PRACNO, long TREATMODENO, long LIQ_ADD_AMOUNT, const std::string& PRACPHASE, long STEPNO)
{
  cleanWhereStatement();

  m_Statement = "Select * from " + m_TableName;

  addWhereClause(CGTE_PP_STIRR_SPEC::PLANT,PLANT);
  addWhereClause(CGTE_PP_STIRR_SPEC::PLANTNO,PLANTNO);
  addWhereClause(CGTE_PP_STIRR_SPEC::PRACNO,PRACNO);
  addWhereClause(CGTE_PP_STIRR_SPEC::TREATMODENO,TREATMODENO);
  addWhereClause(CGTE_PP_STIRR_SPEC::LIQ_ADD_AMOUNT,LIQ_ADD_AMOUNT);
  addWhereClause(CGTE_PP_STIRR_SPEC::PRACPHASE,PRACPHASE);
  addWhereClause(CGTE_PP_STIRR_SPEC::STEPNO,STEPNO);
  m_Statement += getWhereStatement() + ";";

  return CSMC_DBData::select();
}

//## ------------------------------------END-GENERATED-CODE---------------------- 

//## ------------------------------------YOUR-CODE------------------------------- 


