//## Copyright (C) 2009 SMS Siemag AG, Germany 
//## Version generated by DBClassCodeUtility BETA 0.6.3 
//## ALL METHODS MARKED AS - //##DBClassCodeUtility - WILL BE OVERWRITTEN, IF DB CLASS RE-GENERATED 
//## MANUALLY IMPLEMENTED METHODS MUST BE LOCATED BELOW THE MARK - "YOUR-CODE" - 


#include "CGTE_PP_PROCESS.h"


//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_PROCESS::PLANT("PLANT");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_PROCESS::PLANTNO("PLANTNO");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_PROCESS::PRACNO("PRACNO");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_PROCESS::TREATMODENO("TREATMODENO");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_PROCESS::LIQ_ADD_AMOUNT("LIQ_ADD_AMOUNT");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_PROCESS::REVTIME("REVTIME");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_PROCESS::DESCR_E("DESCR_E");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_PROCESS::DESCR_C("DESCR_C");
//##DBClassCodeUtility ! DO NOT EDIT !
const std::string CGTE_PP_PROCESS::USERCODE("USERCODE");

//##DBClassCodeUtility ! DO NOT EDIT !
CGTE_PP_PROCESS::CGTE_PP_PROCESS(cCBS_StdConnection* Connection)
:CSMC_DBData("GTE_PP_PROCESS",Connection)
{
  //please implement virtual method, to initialize your members  
  doOnConstruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
CGTE_PP_PROCESS::CGTE_PP_PROCESS(cCBS_Connection* Connection)
:CSMC_DBData("GTE_PP_PROCESS",Connection)
{
  //please implement virtual method, to initialize your members  
  doOnConstruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
CGTE_PP_PROCESS::CGTE_PP_PROCESS()
:CSMC_DBData("GTE_PP_PROCESS")
{
  //please implement virtual method, to initialize your members  
  doOnConstruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
CGTE_PP_PROCESS::~CGTE_PP_PROCESS()
{
  //please implement virtual method, to destruct your members
  doOnDestruct(); 
}

//##DBClassCodeUtility ! DO NOT EDIT !
std::string CGTE_PP_PROCESS::getPLANT(long Row)
{
  return getString(CGTE_PP_PROCESS::PLANT, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_PROCESS::setPLANT(const std::string& value)
{
  setString(CGTE_PP_PROCESS::PLANT, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_PROCESS::getPLANTNO(long Row)
{
  return getLong(CGTE_PP_PROCESS::PLANTNO, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_PROCESS::setPLANTNO(long value)
{
  setLong(CGTE_PP_PROCESS::PLANTNO, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_PROCESS::getPRACNO(long Row)
{
  return getLong(CGTE_PP_PROCESS::PRACNO, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_PROCESS::setPRACNO(long value)
{
  setLong(CGTE_PP_PROCESS::PRACNO, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_PROCESS::getTREATMODENO(long Row)
{
  return getLong(CGTE_PP_PROCESS::TREATMODENO, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_PROCESS::setTREATMODENO(long value)
{
  setLong(CGTE_PP_PROCESS::TREATMODENO, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
long CGTE_PP_PROCESS::getLIQ_ADD_AMOUNT(long Row)
{
  return getLong(CGTE_PP_PROCESS::LIQ_ADD_AMOUNT, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_PROCESS::setLIQ_ADD_AMOUNT(long value)
{
  setLong(CGTE_PP_PROCESS::LIQ_ADD_AMOUNT, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
CDateTime CGTE_PP_PROCESS::getREVTIME(long Row)
{
  CDateTime D;
  D.fromDBString(getString(CGTE_PP_PROCESS::REVTIME, Row));
  return D;
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_PROCESS::setREVTIME(const CDateTime& value)
{
 setString(CGTE_PP_PROCESS::REVTIME, value.toDBString());
}

//##DBClassCodeUtility ! DO NOT EDIT !
std::string CGTE_PP_PROCESS::getDESCR_E(long Row)
{
  return getString(CGTE_PP_PROCESS::DESCR_E, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_PROCESS::setDESCR_E(const std::string& value)
{
  setString(CGTE_PP_PROCESS::DESCR_E, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
std::string CGTE_PP_PROCESS::getDESCR_C(long Row)
{
  return getString(CGTE_PP_PROCESS::DESCR_C, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_PROCESS::setDESCR_C(const std::string& value)
{
  setString(CGTE_PP_PROCESS::DESCR_C, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
std::string CGTE_PP_PROCESS::getUSERCODE(long Row)
{
  return getString(CGTE_PP_PROCESS::USERCODE, Row);
}

//##DBClassCodeUtility ! DO NOT EDIT !
void CGTE_PP_PROCESS::setUSERCODE(const std::string& value)
{
  setString(CGTE_PP_PROCESS::USERCODE, value);
}

//##DBClassCodeUtility ! DO NOT EDIT !
bool CGTE_PP_PROCESS::select(const std::string& PLANT, long PLANTNO, long PRACNO, long TREATMODENO, long LIQ_ADD_AMOUNT)
{
  cleanWhereStatement();

  m_Statement = "Select * from " + m_TableName;

  addWhereClause(CGTE_PP_PROCESS::PLANT,PLANT);
  addWhereClause(CGTE_PP_PROCESS::PLANTNO,PLANTNO);
  addWhereClause(CGTE_PP_PROCESS::PRACNO,PRACNO);
  addWhereClause(CGTE_PP_PROCESS::TREATMODENO,TREATMODENO);
  addWhereClause(CGTE_PP_PROCESS::LIQ_ADD_AMOUNT,LIQ_ADD_AMOUNT);
  m_Statement += getWhereStatement() + ";";

  return CSMC_DBData::select();
}

//## ------------------------------------END-GENERATED-CODE---------------------- 

//## ------------------------------------YOUR-CODE------------------------------- 


