//## Copyright (C) 2013 SMS Siemag AG, Germany 
//## Version generated by DBClassCodeUtility BETA 0.6.3 
//## ALL METHODS MARKED AS - //##DBClassCodeUtility - WILL BE OVERWRITTEN, IF DB CLASS RE-GENERATED 
//## MANUALLY IMPLEMENTED METHODS MUST BE LOCATED BELOW THE MARK - "YOUR-CODE" - 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CPDH_LANCE_DATA_INCLUDED
#define _INC_CPDH_LANCE_DATA_INCLUDED

#include "CSMC_DBData.h"

class CPDH_LANCE_DATA
: public CSMC_DBData

{

public:
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string HM_ID;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string TREATID;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string PLANT;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string LANCE_NO;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string LANCE_IN_USE_HEAT;
  //##DBClassCodeUtility ! DO NOT EDIT !
  static const std::string LANCE_IN_USE_TOTAL;

  //##DBClassCodeUtility ! DO NOT EDIT !
  CPDH_LANCE_DATA(cCBS_StdConnection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CPDH_LANCE_DATA(cCBS_Connection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  CPDH_LANCE_DATA();

  //##DBClassCodeUtility ! DO NOT EDIT !
  ~CPDH_LANCE_DATA();

  //##DBClassCodeUtility ! DO NOT EDIT !
  std::string getHM_ID(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setHM_ID(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  std::string getTREATID(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setTREATID(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  std::string getPLANT(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setPLANT(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  long getLANCE_NO(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setLANCE_NO(long value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  long getLANCE_IN_USE_HEAT(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setLANCE_IN_USE_HEAT(long value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  long getLANCE_IN_USE_TOTAL(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setLANCE_IN_USE_TOTAL(long value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  bool select(const std::string& HM_ID, const std::string& TREATID, const std::string& PLANT, long LANCE_NO);

  //## ----------------------------------END-GENERATED-CODE--------------------- 

  //## ----------------------------------YOUR-CODE------------------------------ 

  bool exists(const string& HMID, const string& TREATID, const string& PLANT, long LANCENO);
  bool doONPowerBlowing(const string& HMID, const string& TREATID, const string& PLANT, long LANCENO,bool pCommit);

};

#endif /* _INC_CPDH_LANCE_DATA_INCLUDED */
