/* Generated name space, using column DEVICENAME */ 
//## Copyright (C) 2012 SMS Siemag AG, Germany
//## Version generated by DBClassCodeUtility BETA 0.6.3 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CDEF_GC_STIRR_DEVICE_INCLUDED
#define _INC_CDEF_GC_STIRR_DEVICE_INCLUDED

#include <string> 

namespace DEF_GC_STIRR_DEVICE
{

/* 

*/ 

 const std::string BypassPlug1 = "BypassPlug1";
 const std::string BypassPlug2 = "BypassPlug2";
 const std::string EmergencyLance = "EmergencyLance";
 const std::string Plug1 = "Plug1";
 const std::string Plug2 = "Plug2";
 const std::string Plug3 = "Plug3";
 const std::string Plug4 = "Plug4"; //SARS

};

#endif /* _INC_CDEF_GC_STIRR_DEVICE_INCLUDED */
