/* Generated name space, using column LOCATION */ 
//## Copyright (C) 2012 SMS Siemag AG, Germany
//## Version generated by DBClassCodeUtility BETA 0.6.3 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CDEF_GC_SCRAP_CONTAINER_LOC_INCLUDED
#define _INC_CDEF_GC_SCRAP_CONTAINER_LOC_INCLUDED

#include <string> 

namespace DEF_GC_SCRAP_CONTAINER_LOC
{

/* 

*/ 

 const long EAF = 3;
 const long MAINT = 1;
 const long UNKNOWN = 0;
 const long YARD = 2;

};

#endif /* _INC_CDEF_GC_SCRAP_CONTAINER_LOC_INCLUDED */
