/* Generated name space, using column TREATMENTPHASE */ 
//## Copyright (C) 2012 SMS Siemag AG, Germany
//## Version generated by DBClassCodeUtility BETA 0.6.3 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CDEF_GC_TREATMENTPHASE_DEF_INCLUDED
#define _INC_CDEF_GC_TREATMENTPHASE_DEF_INCLUDED

#include <string> 

namespace DEF_GC_TREATMENTPHASE_DEF
{

/* 

*/ 

 const std::string BskAndLiqChgNo = "BskAndLiqChgNo:";
 const std::string HeatingNo = "HeatingNo:";
 const std::string HeatLiqChgNo = "HeatLiqChgNo:";
 const std::string MeltBskNo = "MeltBskNo:";
 const std::string Preparation = "Preparation";
 const std::string Refining = "Refining";
 const std::string Tapping = "Tapping";

};

#endif /* _INC_CDEF_GC_TREATMENTPHASE_DEF_INCLUDED */
