/* Generated name space, using column THERMSTATID */ 
//## Copyright (C) 2012 SMS Siemag AG, Germany
//## Version generated by DBClassCodeUtility BETA 0.6.3 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CDEF_GC_THERM_STAT_INCLUDED
#define _INC_CDEF_GC_THERM_STAT_INCLUDED

#include <string> 

namespace DEF_GC_THERM_STAT
{

/* 

*/ 

 const std::string C = "C";
 const std::string H = "H";
 const std::string M = "M";

};

#endif /* _INC_CDEF_GC_THERM_STAT_INCLUDED */
