/* Generated name space, using column LADLEPARTDESCR */ 
//## Copyright (C) 2012 SMS Siemag AG, Germany
//## Version generated by DBClassCodeUtility BETA 0.6.3 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CDEF_GC_LADLE_PARTS_INCLUDED
#define _INC_CDEF_GC_LADLE_PARTS_INCLUDED

#include <string> 

namespace DEF_GC_LADLE_PARTS
{

/* 

*/ 

 const std::string BottomPlate = "BP";
 const std::string LadleBottom = "LB";
 const std::string LadleWall = "LW";
 const std::string LowerNozzle = "LN";
 const std::string PlateLining = "PL";
 const std::string PorousPlug3 = "PP3";
 const std::string PorousPlug1 = "PP1";
 const std::string PorousPlug2 = "PP2";
 const std::string SafetyLining = "SL";
 const std::string SlideGate = "SG";
 const std::string UpperNozzle = "UN";
 const std::string Wellblock1 = "WB1";
 const std::string Wellblock2 = "WB2";
 const std::string Wellblock3 = "WB3";
 const std::string LadleLife = "LL";
 const std::string TBarLife = "TBL";

};

#endif /* _INC_CDEF_GC_LADLE_PARTS_INCLUDED */
