/* Generated name space, using column PLANT */ 
//## Copyright (C) 2012 SMS Siemag AG, Germany
//## Version generated by DBClassCodeUtility BETA 0.6.3 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CDEF_GC_PLANT_DEF_INCLUDED
#define _INC_CDEF_GC_PLANT_DEF_INCLUDED

#include <string> 

namespace DEF_GC_PLANT_DEF
{

/* 

*/ 

 const std::string AOD = "AOD";
 const std::string CCS = "CCS";
 const std::string EAF = "EAF";
 const std::string HMD = "HMD";
 const std::string L3 = "L3";
 const std::string LF = "LF";

 const std::string YARD = "YARD";


};

#endif /* _INC_CDEF_GC_PLANT_DEF_INCLUDED */
