/* Generated name space, using column MEMBER_ROLE_DESC */ 
//## Copyright (C) 2012 SMS Siemag AG, Germany
//## Version generated by DBClassCodeUtility BETA 0.6.3 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CDEF_GC_MEMBER_ROLE_CAT_INCLUDED
#define _INC_CDEF_GC_MEMBER_ROLE_CAT_INCLUDED

#include <string> 

namespace DEF_GC_MEMBER_ROLE_CAT
{

/* 

*/ 

 const long Melter = 3;
 const long Operator = 2;
 const long Supervisor = 1;

};

#endif /* _INC_CDEF_GC_MEMBER_ROLE_CAT_INCLUDED */
