//## Copyright (C) 2009 SMS Siemag AG, Germany 
//## Version generated by DBClassCodeUtility BETA 0.5.8 
//## ALL METHODS MARKED AS - //##DBClassCodeUtility - WILL BE OVERWRITTEN, IF DB CLASS RE-GENERATED 
//## MANUALLY IMPLEMENTED METHODS MUST BE LOCATED BELOW THE MARK - "YOUR-CODE" - 

#if defined (_MSC_VER) && (_MSC_VER >= 1000)
#pragma once
#endif
#ifndef _INC_CMDB_MAT_ANALYSIS_ELEMENTS_INCLUDED
#define _INC_CMDB_MAT_ANALYSIS_ELEMENTS_INCLUDED

#include "CSMC_DBData.h"

class CMDB_MAT_ANALYSIS_ELEMENTS
: public CSMC_DBData
{

public:

  //##DBClassCodeUtility ! DO NOT EDIT !
  CMDB_MAT_ANALYSIS_ELEMENTS(cCBS_Connection* Connection);

  //##DBClassCodeUtility ! DO NOT EDIT !
  ~CMDB_MAT_ANALYSIS_ELEMENTS();

  //##DBClassCodeUtility ! DO NOT EDIT !
  std::string getMATERIAL_ID(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setMATERIAL_ID(const std::string& value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  long getELEMENT_CODE(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setELEMENT_CODE(long value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  double getVALUE(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setVALUE(double value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  double getAIR_OX_YIELD(long Row);

  //##DBClassCodeUtility ! DO NOT EDIT !
  void setAIR_OX_YIELD(double value);

  //##DBClassCodeUtility ! DO NOT EDIT !
  bool select(const std::string& MATERIAL_ID, long ELEMENT_CODE);

  //## ----------------------------------END-GENERATED-CODE--------------------- 

  //## ----------------------------------YOUR-CODE------------------------------ 

};

#endif /* _INC_CMDB_MAT_ANALYSIS_ELEMENTS_INCLUDED */
